<?php

return [
    'superadmin_email' => env('INVENTORY_SUPERADMIN_EMAIL'),
    'superadmin_username' => env('INVENTORY_SUPERADMIN_USERNAME'),
    'roles' => [
        [
            'slug' => 'superadmin',
            'name' => 'Super Admin',
            'is_superadmin' => true,
            'sidebar_item_keys' => ['*'],
        ],
        [
            'slug' => 'employee',
            'name' => 'Employee',
            'is_superadmin' => false,
            'sidebar_item_keys' => ['employees', 'calendar'],
        ],
        [
            'slug' => 'division-chief',
            'name' => 'FAD Division Chief',
            'is_superadmin' => false,
            'sidebar_item_keys' => [
                'dashboard',
                'inventory',
                'inventory.index',
                'inventory.tabs.moto-vehicle',
                'inventory.tabs.cip',
                'inventory.tabs.machine-equipment',
                'inventory.tabs.office-equipment',
                'inventory.tabs.technical-scientific-equipment',
                'inventory.tabs.other-ppe',
                'inventory.tabs.furniture-fixtures',
                'inventory.tabs.military-police-security',
                'employees',
                'calendar',
                'leave-applications',
            ],
        ],
        [
            'slug' => 'division-chief-ord',
            'name' => 'ORD Division Chief',
            'is_superadmin' => false,
            'sidebar_item_keys' => [
                'dashboard',
                'inventory',
                'inventory.index',
                'inventory.tabs.moto-vehicle',
                'inventory.tabs.cip',
                'inventory.tabs.machine-equipment',
                'inventory.tabs.office-equipment',
                'inventory.tabs.technical-scientific-equipment',
                'inventory.tabs.other-ppe',
                'inventory.tabs.furniture-fixtures',
                'inventory.tabs.military-police-security',
                'employees',
                'calendar',
                'leave-applications',
            ],
        ],
        [
            'slug' => 'division-chief-msesdd',
            'name' => 'MSESDD Division Chief',
            'is_superadmin' => false,
            'sidebar_item_keys' => [
                'dashboard',
                'inventory',
                'inventory.index',
                'inventory.tabs.moto-vehicle',
                'inventory.tabs.cip',
                'inventory.tabs.machine-equipment',
                'inventory.tabs.office-equipment',
                'inventory.tabs.technical-scientific-equipment',
                'inventory.tabs.other-ppe',
                'inventory.tabs.furniture-fixtures',
                'inventory.tabs.military-police-security',
                'employees',
                'calendar',
                'leave-applications',
            ],
        ],
        [
            'slug' => 'division-chief-mmd',
            'name' => 'MMD Division Chief',
            'is_superadmin' => false,
            'sidebar_item_keys' => [
                'dashboard',
                'inventory',
                'inventory.index',
                'inventory.tabs.moto-vehicle',
                'inventory.tabs.cip',
                'inventory.tabs.machine-equipment',
                'inventory.tabs.office-equipment',
                'inventory.tabs.technical-scientific-equipment',
                'inventory.tabs.other-ppe',
                'inventory.tabs.furniture-fixtures',
                'inventory.tabs.military-police-security',
                'employees',
                'calendar',
                'leave-applications',
            ],
        ],
        [
            'slug' => 'hr',
            'name' => 'HR',
            'is_superadmin' => false,
            'sidebar_item_keys' => ['employees', 'calendar', 'leave-applications', 'leave-ledgers'],
        ],
        [
            'slug' => 'rd',
            'name' => 'Regional Director',
            'is_superadmin' => false,
            'sidebar_item_keys' => ['employees', 'calendar', 'leave-applications'],
        ],
    ],
    'sidebar_items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'route_name' => 'inventory.dashboard',
            'route_pattern' => 'inventory.dashboard',
            'icon' => 'bi bi-speedometer2',
            'parent_key' => null,
            'sort_order' => 10,
        ],
        [
            'key' => 'inventory',
            'label' => 'Inventory',
            'route_name' => null,
            'route_pattern' => 'inventory.*',
            'icon' => 'bi bi-archive',
            'parent_key' => null,
            'sort_order' => 20,
        ],
        [
            'key' => 'inventory.index',
            'label' => 'Inventory',
            'route_name' => 'inventory.index',
            'route_pattern' => 'inventory.index',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 10,
        ],
        [
            'key' => 'inventory.tabs.moto-vehicle',
            'label' => 'Motor Vehicle',
            'route_name' => 'inventory.tabs.moto-vehicle',
            'route_pattern' => 'inventory.tabs.moto-vehicle',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 20,
        ],
        [
            'key' => 'inventory.tabs.cip',
            'label' => 'CIP',
            'route_name' => 'inventory.tabs.cip',
            'route_pattern' => 'inventory.tabs.cip',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 30,
        ],
        [
            'key' => 'inventory.tabs.machine-equipment',
            'label' => 'Machine & Equipment',
            'route_name' => 'inventory.tabs.machine-equipment',
            'route_pattern' => 'inventory.tabs.machine-equipment',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 40,
        ],
        [
            'key' => 'inventory.tabs.office-equipment',
            'label' => 'Office Equipment',
            'route_name' => 'inventory.tabs.office-equipment',
            'route_pattern' => 'inventory.tabs.office-equipment',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 50,
        ],
        [
            'key' => 'inventory.tabs.technical-scientific-equipment',
            'label' => 'Technical and Scientific Equipment',
            'route_name' => 'inventory.tabs.technical-scientific-equipment',
            'route_pattern' => 'inventory.tabs.technical-scientific-equipment',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 60,
        ],
        [
            'key' => 'inventory.tabs.other-ppe',
            'label' => 'Other PPE',
            'route_name' => 'inventory.tabs.other-ppe',
            'route_pattern' => 'inventory.tabs.other-ppe',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 70,
        ],
        [
            'key' => 'inventory.tabs.furniture-fixtures',
            'label' => 'Furnitures and Fixtures',
            'route_name' => 'inventory.tabs.furniture-fixtures',
            'route_pattern' => 'inventory.tabs.furniture-fixtures',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 80,
        ],
        [
            'key' => 'inventory.tabs.military-police-security',
            'label' => 'Military, Police & Security Equipment',
            'route_name' => 'inventory.tabs.military-police-security',
            'route_pattern' => 'inventory.tabs.military-police-security',
            'icon' => null,
            'parent_key' => 'inventory',
            'sort_order' => 90,
        ],
        [
            'key' => 'inventory.ipm',
            'label' => 'IPM',
            'route_name' => 'inventory.ipm',
            'route_pattern' => 'inventory.ipm',
            'icon' => 'bi bi-clipboard-check',
            'parent_key' => null,
            'sort_order' => 30,
        ],
        [
            'key' => 'inventory.icm',
            'label' => 'ICM',
            'route_name' => 'inventory.icm',
            'route_pattern' => 'inventory.icm',
            'icon' => 'bi bi-tools',
            'parent_key' => null,
            'sort_order' => 40,
        ],
        [
            'key' => 'roles',
            'label' => 'Roles',
            'route_name' => 'roles.index',
            'route_pattern' => 'roles.*',
            'icon' => 'bi bi-sliders',
            'parent_key' => null,
            'sort_order' => 45,
        ],
        [
            'key' => 'employees',
            'label' => 'Employees',
            'route_name' => 'employees.index',
            'route_pattern' => 'employees.*',
            'icon' => 'bi bi-people',
            'parent_key' => null,
            'sort_order' => 50,
        ],
        [
            'key' => 'calendar',
            'label' => 'Calendar',
            'route_name' => 'calendar.index',
            'route_pattern' => 'calendar.*',
            'icon' => 'bi bi-calendar3',
            'parent_key' => null,
            'sort_order' => 60,
        ],
        [
            'key' => 'leave-applications',
            'label' => 'Leave Applications',
            'route_name' => 'leave-applications.index',
            'route_pattern' => 'leave-applications.*',
            'icon' => 'bi bi-file-earmark-text',
            'parent_key' => 'leave-credits',
            'sort_order' => 20,
        ],
        [
            'key' => 'leave-ledgers',
            'label' => 'Leave Ledgers',
            'route_name' => 'leave-ledgers.index',
            'route_pattern' => 'leave-ledgers.*',
            'icon' => 'bi bi-journal-text',
            'parent_key' => 'leave-credits',
            'sort_order' => 30,
        ],
        [
            'key' => 'leave-credits',
            'label' => 'Leave Credits',
            'route_name' => null,
            'route_pattern' => 'credits.*',
            'icon' => 'bi bi-wallet2',
            'parent_key' => null,
            'sort_order' => 70,
        ],
        [
            'key' => 'credits.cto',
            'label' => 'CTO',
            'route_name' => 'credits.cto',
            'route_pattern' => 'credits.cto',
            'icon' => null,
            'parent_key' => 'leave-credits',
            'sort_order' => 10,
        ],
    ],
];
